debug: true

spring:
  datasource:
    #    url: jdbc:postgresql://dpg-d5unult6ubrc73bt1rq0-a.singapore-postgres.render.com:5432/task_management_0ok9?sslmode=require
    #    username: task_management_0ok9_user
    #    password: lxy0Sh84Koesc2w4aVYOspTVMqzwJaz3
    #    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://db.knxxlzouxoflrhcaejhv.supabase.co:6543/postgres?sslmode=require}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres} #wrong password, but it will be overridden by the environment variable
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
cloudinary:
  cloud-name: dbjroxnkb
  api-key: 646188637996694
  api-secret: dShjOkvvu47SjVyc4vjaj_blCoE


server:
  port: 8080
  servlet:
    context-path: /api/v1
jwt:
  signerKey: "43b5decd-40ea-40d4-b81c-c2aef8e6ccae"
